### ISSUE TITLE
Image module needs feature-flag 

### ISSUE THREAD

**Issue by maujim** [psychon/x11rb#570]
disCurrently, adding x11rb as a dependency in `Cargo.toml` without any feature flags leads to a E0432. 

<details>
<summary>Minimum reproducible example</summary>

```rust
// src/main.rs

use x11rb::image::*;

fn main() {
    println!("Hello, world!");
}
```

```toml
# Cargo.toml

[package]
name = "x11rb-test"
version = "0.1.0"
authors = ["maujim <mauji.mukund@yahoo.ca>"]
edition = "2018"

[dependencies]
x11rb = "0.7.0"
```
</details>

Adding the image module as a feature flag solves this problem. 

<details>
<summary>Solution</summary>

```rust
// src/main.rs

use x11rb::image::*;

fn main() {
    println!("Hello, world!");
}
```

```toml
# Cargo.toml

[package]
name = "x11rb-test"
version = "0.1.0"
authors = ["maujim <mauji.mukund@yahoo.ca>"]
edition = "2018"

[dependencies.x11rb]
version = "0.7.0"
features = ["image"]
```
</details>

However, the documentation (specifically https://docs.rs/x11rb/0.7.0/x11rb/index.html#feature-flags) doesn't list the image module as one that needs a dedicated feature flag, so I think that needs to be updated. Also, it would be good to mention this at the top of `examples/display_ppm.rs` as well. 

Note: I'm pretty new to Rust and its possible that this isn't a bug and I'm just importing things wrong. If that's the case, please let me know how I'd go about using the image module.
